pub mod build_cache;
pub mod builder;
pub mod certificate;
pub mod checker;
pub mod clause_set;
pub mod cleaner;
pub mod code_generator;
pub mod common;
pub mod compilation;
pub mod display;
pub mod doc_generator;
pub mod elaborator;
pub mod generalization_set;
pub mod generative;
pub mod interfaces;
pub mod kernel;
pub mod manifest;
pub mod module;
pub mod monomorphizer;
pub mod normalizer;
pub mod ort_utils;
pub mod pattern_tree;
pub mod processor;
pub mod project;
pub mod proof_step;
pub mod prover;
pub mod saturation;
pub mod server;
pub mod syntax;
pub mod term_graph;
pub mod verifier;

#[cfg(test)]
mod tests;
